# 📄 Documentation label: triggered by any markdown file changes
📄-documentation:
  - changed-files:
      - any-glob-to-any-file: '**/*.md'

# 🌟 Feature label: triggered by head branch names starting with 'feature'
🌟-feature:
  - head-branch:
      - '^feature'
      - 'feature'

# 🚀 Release label: triggered on PRs targeting the 'main' branch
🚀-release:
  - base-branch: 'main'

# 🛠️ Source label: triggered by changes under 'src' excluding docs
🛠️-source:
  - all:
      - changed-files:
          - any-glob-to-any-file: 'src/**/*'
          - all-globs-to-all-files: '!src/docs/*'
