Documentation:
- changed-files:
  - any-glob-to-any-file: '**/*.md'
bug:
  - 'src/**'
  - '**/bugfix/**'



test:
  - 'tests/**'

feature:
 - head-branch: ['^feature', 'feature']

# Add 'release' label to any PR that is opened against the `main` branch
release:
 - base-branch: 'main'

source:
- all:
  - changed-files:
    - any-glob-to-any-file: 'src/**/*'
    - all-globs-to-all-files: '!src/docs/*'