Documentation:
- changed-files:
  - any-glob-to-any-file: '**/*.md'


feature:
 - head-branch: ['^feature', 'feature']

# Add 'release' label to any PR that is opened against the `main` branch
release:
 - base-branch: 'main'

source:
- all:
  - changed-files:
    - any-glob-to-any-file: 'src/**/*'
    - all-globs-to-all-files: '!src/docs/*'

bug:
  - pr-title:
    - '^bug'
    - 'bug'

bug:
  - pr-title:
    - '.*bug.*'

test:
  - pr-title:
    - '.*test.*'
