services:
  app:
    build: .
    container_name: redirector
    ports:
      - "80:80"
    volumes:
      - ./data:/app/data
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: unless-stopped
  redis:
    image: redis:8.0.1-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
