# URL Shortener Configuration
# Define your static and dynamic redirects here.
# Example:
# [static]
# google = "https://www.google.com"
#
# [dynamic]
# meetwith = "https://g.co/meet/{name}"

[static]

[dynamic]
