"""init

Revision ID: f200f245867a
Revises: 
Create Date: 2025-06-09 01:47:38.100455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f200f245867a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('redirects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('pattern', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.Column('created_ip', sa.String(), nullable=True),
    sa.Column('updated_ip', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('redirects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_redirects_pattern'), ['pattern'], unique=True)

    op.create_table('upstream_cache',
    sa.Column('pattern', sa.String(), nullable=False),
    sa.Column('upstream_name', sa.String(), nullable=False),
    sa.Column('resolved_url', sa.String(), nullable=True),
    sa.Column('checked_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('pattern', 'upstream_name')
    )
    op.create_table('upstream_check_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pattern', sa.Text(), nullable=False),
    sa.Column('upstream_name', sa.Text(), nullable=False),
    sa.Column('check_url', sa.Text(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('tried_at', sa.String(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('cached', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pattern', 'upstream_name', name='uq_pattern_upstream')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('upstream_check_log')
    op.drop_table('upstream_cache')
    with op.batch_alter_table('redirects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_redirects_pattern'))

    op.drop_table('redirects')
    # ### end Alembic commands ###
