name: Docker Image CI

on:
  workflow_run:
    workflows: ["Validate"]
    types: [completed]

jobs:
  build:
    # Only run if tests passed in the triggering workflow
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      # Set IMAGE_NAME environment variable
      - name: Set image name
        run: echo "IMAGE_NAME=redirector" >> $GITHUB_ENV

      # Checkout the repo from the triggering workflow's branch
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      # Get branch and commit SHA for tagging
      - name: Set Docker tag using commit SHA
        id: tag
        run: |
          BRANCH=${{ github.event.workflow_run.head_branch }}
          COMMIT_SHA=$(git rev-parse --short HEAD)
          echo "Branch is: $BRANCH"
          echo "Short SHA is: $COMMIT_SHA"

          if [[ "$BRANCH" == "develop" ]]; then
            echo "DOCKER_TAG=dev" >> $GITHUB_ENV
          elif [[ "$BRANCH" == "main" ]]; then
            echo "DOCKER_TAG=latest" >> $GITHUB_ENV
          fi

          echo "COMMIT_SHA=$COMMIT_SHA" >> $GITHUB_ENV

      # Set up Python environment (optional - if needed by build)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Install Python dependencies (optional)
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Build Docker image using commit SHA as tag
      - name: Build Docker image
        run: |
          docker build . -f Dockerfile -t $IMAGE_NAME:$COMMIT_SHA

      # Log in to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Tag Docker images
      - name: Tag Docker images
        run: |
          docker tag $IMAGE_NAME:$COMMIT_SHA ${{ secrets.DOCKER_HUB_USERNAME }}/$IMAGE_NAME:$DOCKER_TAG
          docker tag $IMAGE_NAME:$COMMIT_SHA ${{ secrets.DOCKER_HUB_USERNAME }}/$IMAGE_NAME:$DOCKER_TAG-$COMMIT_SHA

      # Push Docker images
      - name: Push Docker images
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/$IMAGE_NAME:$DOCKER_TAG
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/$IMAGE_NAME:$DOCKER_TAG-$COMMIT_SHA
