name: Release on master

permissions:
  contents: read
  packages: write
  actions: write

on:
  push:
    branches:
      - master
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Get version from app/CONSTANTS.py
        id: get_version
        run: |
          VERSION=$(python -c "import sys; sys.path.insert(0, 'app'); from CONSTANTS import get_semver; print(get_semver())")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          name: Release v${{ steps.get_version.outputs.version }}
          body: |
            Automated release for version ${{ steps.get_version.outputs.version }}.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets (optional)
        uses: softprops/action-gh-release@v2
        if: always()
        with:
          files: |
            README.md
            requirements.txt
            Dockerfile
            docker-compose.yml
            app/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
